In [2]:
import pandas as pd
import numpy as np

In [6]:
pwd

'C:\\Users\\sohaa\\Downloads\\CHALLENGES'

In [8]:
df=pd.read_csv('C:\\Users\\sohaa\\Downloads\\CHALLENGES\\Back order prediction\\Training_Dataset_v2.csv')

c:\users\sohaa\anaconda3\envs\tfodab\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
df.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,No
1,1043384,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.99,0.99,0.0,No,No,No,Yes,No,No
2,1043696,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
3,1043852,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.10,0.13,0.0,No,No,No,Yes,No,No
4,1044048,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No

In [17]:
df1=df.iloc[:,1:]

In [18]:
df1.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,No
1,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.99,0.99,0.0,No,No,No,Yes,No,No
2,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
3,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.10,0.13,0.0,No,No,No,Yes,No,No
4,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No

In [22]:
df1.describe()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty
count,1.687860e+06,1.586967e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06
mean,4.961118e+02,7.872267e+00,4.405202e+01,1.781193e+02,3.449867e+02,5.063644e+02,5.592607e+01,1.750259e+02,3.417288e+02,5.252697e+02,5.277230e+01,2.043724e+00,-6.872059e+00,-6.437947e+00,6.264507e-01
std,2.961523e+04,7.056024e+00,1.342742e+03,5.026553e+03,9.795152e+03,1.437892e+04,1.928196e+03,5.192378e+03,9.613167e+03,1.483861e+04,1.254983e+03,2.360165e+02,2.655636e+01,2.584333e+01,3.372224e+01
min,-2.725600e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.900000e+01,-9.900000e+01,0.000000e+00
25%,4.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.300000e-01,6.600000e-01,0.000000e+00
50%,1.500000e+01,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,8.200000e-01,8.100000e-01,0.000000e+00
75%,8.000000e+01,9.000000e+00,0.000000e+00,4.000000e+00,1.200000e+01,2.000000e+01,4.000000e+00,1.500000e+01,3.100000e+01,4.700000e+01,3.000000e+00,0.000000e+00,9.700000e-01,9.500000e-01,0.000000e+00
max,1.233440e+07,5.200000e+01,4.894080e+05,1.427612e+06,2.461360e+06,3.777304e+06,7.417740e+05,1.105478e+06,2.146625e+06,3.205172e+06,3.133190e+05,1.464960e+05,1.000000e+00,1.000000e+00,1.253000e+04

In [24]:
df1.count()

national_inv         1687860
lead_time            1586967
in_transit_qty       1687860
forecast_3_month     1687860
forecast_6_month     1687860
forecast_9_month     1687860
sales_1_month        1687860
sales_3_month        1687860
sales_6_month        1687860
sales_9_month        1687860
min_bank             1687860
potential_issue      1687860
pieces_past_due      1687860
perf_6_month_avg     1687860
perf_12_month_avg    1687860
local_bo_qty         1687860
deck_risk            1687860
oe_constraint        1687860
ppap_risk            1687860
stop_auto_buy        1687860
rev_stop             1687860
went_on_backorder    1687860
dtype: int64

In [44]:
df1.isnull().sum()

national_inv         1
lead_time            0
in_transit_qty       1
forecast_3_month     1
forecast_6_month     1
forecast_9_month     1
sales_1_month        1
sales_3_month        1
sales_6_month        1
sales_9_month        1
min_bank             1
potential_issue      1
pieces_past_due      1
perf_6_month_avg     1
perf_12_month_avg    1
local_bo_qty         1
deck_risk            1
oe_constraint        1
ppap_risk            1
stop_auto_buy        1
rev_stop             1
went_on_backorder    1
dtype: int64

In [43]:
df1['lead_time'].replace(np.NAN,np.mean(df1['lead_time']),inplace=True)

In [40]:
df1['oe_constraint'].unique()

array(['No', 'Yes', nan], dtype=object)

In [46]:
df1.dropna(inplace=True)

In [47]:
df1.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,0.0,7.872267,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,No
1,2.0,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.99,0.99,0.0,No,No,No,Yes,No,No
2,2.0,7.872267,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
3,7.0,8.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.10,0.13,0.0,No,No,No,Yes,No,No
4,8.0,7.872267,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No

In [48]:
df1.corr()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty
national_inv,1.000000,0.003318,0.098238,0.078199,0.079744,0.078948,0.147449,0.192605,0.225067,0.239613,0.399969,0.030677,-0.013544,-0.010732,0.014887
lead_time,0.003318,1.000000,-0.006844,-0.008008,-0.008511,-0.008736,-0.005609,-0.006758,-0.007097,-0.007239,-0.007088,-0.001500,-0.048434,-0.045530,-0.001255
in_transit_qty,0.098238,-0.006844,1.000000,0.662648,0.687768,0.679152,0.619270,0.698417,0.689908,0.659372,0.749974,0.167460,0.003282,0.004292,0.066612
forecast_3_month,0.078199,-0.008008,0.662648,1.000000,0.990490,0.977337,0.684494,0.781178,0.835585,0.825539,0.725042,0.361214,0.008445,0.008694,0.039419
forecast_6_month,0.079744,-0.008511,0.687768,0.990490,1.000000,0.994945,0.701770,0.808755,0.868099,0.858253,0.738553,0.363147,0.008343,0.008499,0.039724
forecast_9_month,0.078948,-0.008736,0.679152,0.977337,0.994945,1.000000,0.716367,0.829911,0.891884,0.881894,0.735891,0.366001,0.008306,0.008421,0.039732
sales_1_month,0.147449,-0.005609,0.619270,0.684494,0.701770,0.716367,1.000000,0.918548,0.867479,0.815959,0.756137,0.249526,0.001163,0.002370,0.066188
sales_3_month,0.192605,-0.006758,0.698417,0.781178,0.808755,0.829911,0.918548,1.000000,0.975594,0.929491,0.856017,0.304565,0.001488,0.002837,0.071030
sales_6_month,0.225067,-0.007097,0.689908,0.835585,0.868099,0.891884,0.867479,0.975594,1.000000,0.971833,0.837110,0.323552,0.002898,0.004221,0.057765
sales_9_month,0.239613,-0.007239,0.659372,0.825539,0.858253,0.881894,0.815959,0.929491,0.971833,1.000000,0.800890,0.317692,0.003438,0.004749,0.048880
min_bank,0.399969,-0.007088,0.749974,0.725042,0.738553,0.735891,0.756137,0.856017,0.837110,0.800890,1.000000,0.262136,-0.002446,0.000409,0.076678
pieces_past_due,0.030677,-0.001500,0.167460,0.361214,0.363147,0.366001,0.249526,0.304565,0.323552,0.317692,0.262136,1.000000,0.001687,0.001783,0.010400
perf_6_month_avg,-0.013544,-0.048434,0.003282,0.008445,0.008343,0.008306,0.001163,0.001488,0.002898,0.003438,-0.002446,0.001687,1.000000,0.968815,0.000944
perf_12_month_avg,-0.010732,-0.045530,0.004292,0.008694,0.008499,0.008421,0.002370,0.002837,0.004221,0.004749,0.000409,0.001783,0.968815,1.000000,0.001390
local_bo_qty,0.014887,-0.001255,0.066612,0.039419,0.039724,0.039732,0.066188,0.071030,0.057765,0.048880,0.076678,0.010400,0.000944,0.001390,1.000000

In [50]:
df1.dtypes

national_inv         float64
lead_time            float64
in_transit_qty       float64
forecast_3_month     float64
forecast_6_month     float64
forecast_9_month     float64
sales_1_month        float64
sales_3_month        float64
sales_6_month        float64
sales_9_month        float64
min_bank             float64
potential_issue       object
pieces_past_due      float64
perf_6_month_avg     float64
perf_12_month_avg    float64
local_bo_qty         float64
deck_risk             object
oe_constraint         object
ppap_risk             object
stop_auto_buy         object
rev_stop              object
went_on_backorder     object
dtype: object

In [52]:
df1.potential_issue.unique()

array(['No', 'Yes'], dtype=object)

In [58]:
df1['potential_issue']=np.where(df1['potential_issue']=='Yes',1,0)

In [65]:
df1.went_on_backorder.unique()

array(['No', 'Yes'], dtype=object)

In [64]:
df1.rev_stop.unique()

array(['No', 'Yes'], dtype=object)

In [67]:
df1['deck_risk']=np.where(df1['deck_risk']=='Yes',1,0)
df1['oe_constraint']=np.where(df1['oe_constraint']=='Yes',1,0)
df1['ppap_risk']=np.where(df1['ppap_risk']=='Yes',1,0)
df1['stop_auto_buy']=np.where(df1['stop_auto_buy']=='Yes',1,0)
df1['rev_stop']=np.where(df1['rev_stop']=='Yes',1,0)
df1['went_on_backorder']=np.where(df1['went_on_backorder']=='Yes',1,0)

In [69]:
df1.dtypes

national_inv         float64
lead_time            float64
in_transit_qty       float64
forecast_3_month     float64
forecast_6_month     float64
forecast_9_month     float64
sales_1_month        float64
sales_3_month        float64
sales_6_month        float64
sales_9_month        float64
min_bank             float64
potential_issue        int32
pieces_past_due      float64
perf_6_month_avg     float64
perf_12_month_avg    float64
local_bo_qty         float64
deck_risk              int32
oe_constraint          int32
ppap_risk              int32
stop_auto_buy          int32
rev_stop               int32
went_on_backorder      int32
dtype: object

In [93]:
X=df1.iloc[:,0:21]
Y=df1.iloc[:,-1]

In [94]:
Y

0          0
1          0
2          0
3          0
4          0
          ..
1687855    0
1687856    0
1687857    1
1687858    0
1687859    0
Name: went_on_backorder, Length: 1687860, dtype: int32

In [71]:
!pip install sklearn

Processing c:\users\sohaa\appdata\local\pip\cache\wheels\23\9d\42\5ec745cbbb17517000a53cecc49d6a865450d1f5cb16dc8a9c\sklearn-0.0-py2.py3-none-any.whl
Collecting scikit-learn
  Downloading scikit_learn-0.23.1-cp36-cp36m-win_amd64.whl (6.8 MB)
Requirement already satisfied: numpy>=1.13.3 in c:\users\sohaa\anaconda3\envs\tfodab\lib\site-packages (from scikit-learn->sklearn) (1.18.4)
Requirement already satisfied: scipy>=0.19.1 in c:\users\sohaa\anaconda3\envs\tfodab\lib\site-packages (from scikit-learn->sklearn) (1.5.0)
Collecting joblib>=0.11
  Downloading joblib-0.15.1-py3-none-any.whl (298 kB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Installing collected packages: joblib, threadpoolctl, scikit-learn, sklearn
Successfully installed joblib-0.15.1 scikit-learn-0.23.1 sklearn-0.0 threadpoolctl-2.1.0

In [95]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [102]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [103]:
X_train

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
1129258,11.0,2.000000,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.33,0.16,0.0,1,0,0,1,0
856132,10.0,12.000000,0.0,50.0,50.0,50.0,0.0,1.0,1.0,1.0,...,0,0.0,0.27,0.26,0.0,1,0,0,1,0
1076576,20.0,12.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.58,0.58,0.0,1,0,0,1,0
972246,304.0,7.872267,0.0,0.0,0.0,0.0,3.0,21.0,45.0,73.0,...,0,0.0,-99.00,-99.00,0.0,1,0,0,1,0
737339,5.0,9.000000,0.0,4.0,8.0,16.0,4.0,7.0,21.0,27.0,...,0,0.0,0.70,0.66,0.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836489,13.0,8.000000,0.0,18.0,24.0,36.0,7.0,19.0,30.0,50.0,...,0,0.0,0.64,0.65,0.0,0,0,0,1,0
491263,1.0,8.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.42,0.36,0.0,0,0,1,1,0
470924,180.0,8.000000,0.0,0.0,0.0,0.0,0.0,10.0,10.0,10.0,...,0,0.0,0.59,0.78,0.0,0,0,0,1,0
491755,0.0,12.000000,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0,0.0,0.63,0.72,0.0,0,0,0,1,0
128037,167.0,12.000000,0.0,0.0,0.0,0.0,0.0,6.0,9.0,11.0,...,0,0.0,0.69,0.68,0.0,0,0,0,1,0

In [106]:
rc=RandomForestClassifier(random_state=1)
rc.fit(X_train,y_train)

RandomForestClassifier(random_state=1)

In [113]:
rc.feature_importances_

array([1.00723886e-01, 4.16375024e-02, 2.63471811e-02, 7.51102685e-02,
       7.83196328e-02, 8.44073432e-02, 5.21878107e-02, 6.71018412e-02,
       7.47322762e-02, 8.72150402e-02, 5.41984867e-02, 1.07800007e-03,
       1.20554954e-02, 9.91778892e-02, 1.01477615e-01, 1.37494443e-02,
       1.17452623e-02, 3.24651428e-04, 1.39337632e-02, 4.42022960e-03,
       5.63800173e-05])

In [157]:
a=np.argmax(rc.feature_importances_)
df1.columns
col=['national_inv','lead_time','in_transit_qty','sales_1_month','sales_3_month','min_bank','potential_issue','pieces_past_due','perf_12_month_avg',
    'local_bo_qty', 'deck_risk', 'oe_constraint',
       'ppap_risk', 'stop_auto_buy', 'rev_stop']

Index(['national_inv', 'lead_time', 'in_transit_qty', 'forecast_3_month',
       'forecast_6_month', 'forecast_9_month', 'sales_1_month',
       'sales_3_month', 'sales_6_month', 'sales_9_month', 'min_bank',
       'potential_issue', 'pieces_past_due', 'perf_6_month_avg',
       'perf_12_month_avg', 'local_bo_qty', 'deck_risk', 'oe_constraint',
       'ppap_risk', 'stop_auto_buy', 'rev_stop', 'went_on_backorder'],
      dtype='object')

In [149]:
ytest1=np.array(y_test)
ytest1.shape

(337572,)

In [108]:
pred=rc.predict(X_test)

In [146]:
from sklearn.metrics import accuracy_score,roc_auc_score
accuracy_score(y_test,pred)

0.9948248077447182

In [152]:
roc_auc_score(y_test,rc.predict_proba(X_test)[:,1])

0.9663524590051937

In [111]:
#pred1=rc.predict(X_train)
accuracy_score(y_train,pred1)

0.9995919389048855

In [168]:
col=['national_inv','lead_time','in_transit_qty','forecast_6_month','sales_1_month','sales_3_month','min_bank','potential_issue','pieces_past_due','perf_12_month_avg',
    'local_bo_qty', 'deck_risk', 'oe_constraint',
       'ppap_risk', 'stop_auto_buy', 'rev_stop']

In [169]:
X1=df1[col]
Y

0          0
1          0
2          0
3          0
4          0
          ..
1687855    0
1687856    0
1687857    1
1687858    0
1687859    0
Name: went_on_backorder, Length: 1687860, dtype: int32

In [170]:
X_train,X_test,y_train,y_test=train_test_split(X1,Y,test_size=0.1,random_state=2)
rc=RandomForestClassifier(random_state=1)
rc.fit(X_train,y_train)
pred=rc.predict(X_test)
accuracy_score(y_test,pred)

0.9947389001457467

In [171]:
pred1=rc.predict(X_train)
accuracy_score(y_train,pred1)

0.9991264415031789